---

- name: mkdir .docker
  file:
    path=/root/.docker
    state=directory
    owner=root
    group=root
    mode=0755
  become: true

- name: setup docker json config
  template:
    src=docker.json.j2
    dest=/root/.docker/config.json
  become: true
