---

- name: stop jenkins
  include: stop.yml

- name: cleanup jenkins home dir
  file: path={{ jenkins_home }} state=absent

- name: cleanup jenkins install dir
  file: path={{ jenkins_install }} state=absent

- name: cleanup jenkins service
  file: path=/etc/systemd/system/jenkins.service state=absent
  become: true

- name: stop docker images
  shell: docker ps -a | grep {{ item[0] }}-{{ item[1] }} | awk '{print $1}' | xargs docker stop
  with_nested:
    - "{{ repos }}"
    - "{{ deploy_envs }}"

- name: rm docker images
  shell: docker ps -a | grep {{ item[0] }}-{{ item[1] }} | awk '{print $1}' | xargs docker rm
  with_nested:
    - "{{ repos }}"
    - "{{ deploy_envs }}"
